config/routes.rb
Rails.application.routes.draw do
  resources :products, only: [:index, :show] do
    resources :reviews
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root 'home#index'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "email", "encrypted_password", "id", "remember_created_at", "reset_password_sent_at", "reset_password_token", "updated_at"]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord

  belongs_to :user
  has_many :cart_items

end

app/models/cart_item.rb
class CartItem < ApplicationRecord

  belongs_to :cart
  belongs_to :product

  validates :quantity, presence: true
  validates :price, presence: true

end

app/models/category.rb
class Category < ApplicationRecord

  has_many :products, dependent: :destroy

  validates :name, presence: true, uniqueness: true

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "id", "name", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["products"]
  end

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :user
  has_many :order_items

  validates :shipping_address, presence: true
  validates :total_amount, presence: true

end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  belongs_to :product

  validates :quantity, presence: true

end

app/models/product.rb
class Product < ApplicationRecord

  has_many :order_items
  has_many :cart_items
  belongs_to :category
  has_many :reviews

  has_many_attached :images

  validates :name, presence: true, uniqueness: true
  validates :description, presence: true
  validates :category, presence: true
  validates :images, presence: true
  validates :quantity, presence: true
  validates :price, presence: true

  def self.ransackable_attributes(auth_object = nil)
    ["category_id", "created_at", "description", "id", "name", "price", "quantity", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["cart_items", "category", "order_items"]
  end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :title, presence: true
  validates :description, presence: true
  validates :rating, presence: true
  validate :rating_greater_than_one

  def rating_greater_than_one
    if rating.present? && rating < 1
      errors.add(:rating, "atLeast give 1 star")
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :cart
  has_many :orders
  has_many :reviews

  validates :name, presence: true, format: { with: /([\w\-\']{2,})([\s]+)([\w\-\']{2,})/ }
  validates :mobile_no, presence: true, format: { with: /\A\d{4}-?\d{6}\z/ }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password,:password_confirmation, :name, :mobile_no)}

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :current_password, :name, :mobile_no)}
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @categories = Category.all.includes(:products)
    @products = []
    if params[:category].present?
      @products = Category.find_by_id(params[:category])&.products
    else
      @products = Product.all
    end
  end

  def show
    @product = Product.find(params[:id])
    @reviews = case params[:review]
               when 'latest'
                 @product.reviews.joins(:user).select('reviews.*, users.name AS review_by').order(created_at: :desc)
               when 'low_to_high'
                 @product.reviews.joins(:user).select('reviews.*, users.name AS review_by').order(rating: :asc)
               when 'high_to_low'
                 @product.reviews.joins(:user).select('reviews.*, users.name AS review_by').order(rating: :desc)
               else
                 @product.reviews.joins(:user).select('reviews.*, users.name AS review_by')
               end
    @review = @product.reviews.new
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token if Rails.env.test?

  def new
    @product = Product.find_by_id(params[:product_id])
    @review = @product.reviews.new
    respond_to do |format|
      format.js { }
    end
  end

  def create
    @product = Product.find_by_id(params[:product_id])
    @review = @product.reviews.new(review_params)
    if @review.save
      flash[:notice] = "Review was successfully created."
      redirect_to @product
    else
      flash[:error] = @review.errors
      redirect_back(fallback_location: product_path(@product))
    end
  end

  def edit
    @product = Product.find_by_id(params[:product_id])
    @review = @product.reviews.find(params[:id])
    respond_to do |format|
      format.js { }
    end
  end

  def update
    @product = Product.find_by_id(params[:product_id])
    @review = @product.reviews.find(params[:id])
    if @review.update(review_params)
      flash[:notice] = "Review was successfully updated."
      redirect_to @product
    else
      flash[:error] = @review.errors
      redirect_back(fallback_location: product_path(@product))
    end
  end

  def destroy
    @product = Product.find_by_id(params[:product_id])
    @review = @product.reviews.find(params[:id])
    @review.destroy
    flash[:notice] = "Review was successfully deleted."
    redirect_to @product
  end

  private
  def review_params
    params.require(:review).permit(:title, :description, :rating, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def rating_stars(rating)
    full_stars = '★' * rating
    empty_stars = '☆' * (5 - rating)
    content = "#{full_stars}#{empty_stars}"

    content_tag(:span, content.html_safe, class: 'star-rating active')
  end
end

app/views/home/index.html.erb
<% if user_signed_in? %>
  <div> Welcome <%= current_user.name %> </div>
  <%= link_to "Edit Profile", edit_user_registration_path %>
  <%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete } %>
<% else %>
  <%= link_to "Sign in", new_user_session_url %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcomDemo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render partial: 'partials/header' %>
  <p class="notice text-success"><%= notice %></p>
  <% if alert.present? %>
    <p class="alert text-danger" style="background-color: #F8D7DA"><%= alert %></p>
  <% end %>
  <div class="h-100">
    <%= yield %>
  </div>
  <div class="footer">
    <%= render partial: 'partials/footer' %>
  </div>
  </body>
</html>

app/views/partials/_footer.html.erb
<footer class="bg-dark p-4 text-center text-white bottom-0">
  <div class="container">
    &copy; <%= Time.now.year %> Ecom company
  </div>
</footer>

app/views/partials/_header.html.erb
<nav class="navbar bg-dark navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Ecom</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "Products", products_path, class: "nav-link text-white" %>
        </li>

      </ul>
      <div class="d-flex">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
            <li class="nav-item"><%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Sign out", destroy_user_session_path, data: { turbo_method: :delete }, class: "nav-link text-white" %></li>
        <% else %>
            <li class="nav-item"><%= link_to "Sign in", new_user_session_url, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Sign Up", new_user_registration_path, class: "nav-link text-white" %></li>
            <li class="nav-item"><%= link_to "Cart", "#", class: "nav-link text-white" %></li>
        <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/products/index.html.erb
<div class="row">
  <div class="col-md-3">
    <h2>Categories</h2>
    <ul class="list-group">
      <li class="list-group-item">
        <%= link_to "All", products_path %>
      </li>
      <% @categories.each do |category| %>
        <li class="list-group-item">
          <%= link_to category.name, products_path(category: category) %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="row row-cols-1 row-cols-md-4">
      <% @products.each do |product| %>
        <div class="col mb-4">
          <div class="card h-100">
            <div class="h-100">
              <%= image_tag(product.images.first, class: "card-img-top", alt: product.name) if product.images.attached? %>
            </div>
            <div class="card-body">
              <h5 class="card-title"><%= product.name %></h5>
              <p class="card-text"><%= product.description[0..20] + "..." %></p>
              <p class="card-text">Price: $<%= product.price %></p>
              <%if product.quantity > 1 %>
                <p class="text-success">Available</p>
              <%else %>
                <p class="text-warning">Out of stock</p>
              <%end %>
              <%= link_to "More...", product_path(product), class: "btn btn-primary" %>
              <%= link_to "Add to cart", product_path(product), class: "btn btn-success" unless product.quantity < 1 %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<!-- app/views/products/show.html.erb -->
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div id="product-carousel" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner h-100">
          <% img_length = 0 %>
          <% @product.images.each_with_index do |image, index| %>
            <% img_length += 1 %>
            <div class="carousel-item<%= ' active' if index.zero? %>">
              <%= image_tag image, class: "d-block w-100", alt: "Product Image #{index + 1}" %>
            </div>
          <% end %>
        </div>
        <% if img_length > 1 %>
          <a class="carousel-control-prev" href="#product-carousel" role="button" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </a>
          <a class="carousel-control-next" href="#product-carousel" role="button" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </a>
        <% end %>
      </div>
    </div>
    <div class="col-md-6">
      <!-- Product details -->
      <h2><%= @product.name %></h2>
      <p><strong>Description:</strong> <%= @product.description %></p>
      <p><strong>Price:</strong> $<%= @product.price %></p>
      <%if @product.quantity > 1 %>
        <p class="text-success">Available</p>
      <%else %>
        <p class="text-warning">Out of stock</p>
      <%end %>
      <div class="d-flex flex-row justify-content-between">
        <%= link_to "Add to cart", product_path(@product), class: "btn btn-success" unless @product.quantity < 1 %>
        <div class="review-sort-dropdown">
          <%= button_tag(class: 'btn btn-secondary dropdown-toggle', type: 'button', id: 'dropdownMenuButton1', 'data-bs-toggle' => 'dropdown', 'aria-expanded' => 'false') do %>
            Sort by
          <% end %>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><%= link_to 'Latest', product_path(@product,review: "latest"), class: "dropdown-item" %></li>
            <li><%= link_to 'Low to High', product_path(@product,review: "low_to_high"), class: "dropdown-item" %></li>
            <li><%= link_to 'High to Low', product_path(@product,review: "high_to_low"), class: "dropdown-item" %></li>
          </ul>
        </div>
      </div>
      <!-- Back button to return to the products list -->
      <%= link_to "Back to Products", products_path, class: "d-block mt-2" %>
      <table class="table">
        <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Description</th>
          <th scope="col">Rating</th>
          <th scope="col">By</th>
          <th scope="col">Added at</th>
        </tr>
        </thead>
        <tbody>
        <% @reviews.each do |review| %>
          <tr>
            <td><%= review.title %></td>
            <td><%= review.description %></td>
            <td><%= rating_stars(review.rating) %></td>
            <td><%= review.review_by %></td>
            <td><%= review.created_at %></td>
            <% if review.user_id == current_user&.id %>
            <td><%= link_to "edit", edit_product_review_path(@product, review), remote: true %></td>
            <td><%= link_to "delete", product_review_path(@product, review), data: { turbo_method: :delete, confirm: "Are you sure!" } %></td>
            <% end %>
          </tr>
        <% end %>
        </tbody>
      </table>
      <%= link_to "Add review", new_product_review_path(@product), remote: true, class: "btn btn-primary" %>
      <div id="review-target"></div>
    </div>
  </div>
</div>

<style>
    .carousel-control-prev,
    .carousel-control-next {
        background-color: rgba(0, 0, 0, 0.5);
        color: white;
        height: 50px;
        width: 50px;
        margin: auto;
        border-radius: 50%;
    }

    .carousel-control-prev-icon,
    .carousel-control-next-icon {
        background-color: transparent;
    }
    .star-rating {
        font-size: 24px;
        cursor: pointer;
        color: gray;
    }

    .star-rating.active {
        color: gold;
    }

</style>

<style>
    .star {
        font-size: 24px;
        cursor: pointer;
        color: gray;
    }

    .star.active {
        color: gold;
    }

    /*.star.hover {*/
    /*    color: gold;*/
    /*}*/

    .rating {
        display: flex;
    }
</style>

<script>
    document.addEventListener("DOMContentLoaded", (event) => {
        $(document).on('click','.star', function() {
            const rating = $(this).data('value');
            $('#rating').val(rating);
            updateStars(rating);
        });

        function updateStars(rating) {
            $('.star').removeClass('active');
            $('.star:lt(' + rating + ')').addClass('active');
        }

    });
</script>

app/views/reviews/_form.html.erb
<h2>Review</h2>
<%= form_for([product, review]) do |form| %>
  <p>
    <%= form.label :title, for: :review_title %>
    <%= form.text_field :title, presence: true, id: :review_title, class: "form-control" %>
    <% if flash[:error].present? && flash[:error]["title"].present? %>
      <div class="error text-danger">
        <%= flash[:error]["title"].join(', ') %>
      </div>
    <% end %>
  </p>
  <p>
    <%= form.label :description, for: :review_description %>
    <%= form.text_area :description, presence: true, id: :review_description, class: "form-control" %>
    <% if flash[:error].present? && flash[:error]["description"].present? %>
      <div class="error text-danger">
        <%= flash[:error]["description"].join(', ') %>
      </div>
    <% end %>
  </p>
  <div class="rating d-block mb-3">
    <%= form.label :rating %>
    <span class="star" data-value="1">&#9733;</span>
    <span class="star" data-value="2">&#9733;</span>
    <span class="star" data-value="3">&#9733;</span>
    <span class="star" data-value="4">&#9733;</span>
    <span class="star" data-value="5">&#9733;</span>
    <%= form.hidden_field :rating, presence: true, id: "rating" %>
    <% if flash[:error].present? && flash[:error]["rating"].present? %>
      <div class="error text-danger">
        <%= flash[:error]["rating"].join(', ') %>
      </div>
    <% end %>
  </div>
  <%= form.hidden_field :user_id, presence: true, value: current_user&.id %>
  <p><%= form.submit class: "btn btn-primary"%></p>
<% end %>

app/views/reviews/edit.js.erb
$("#review-target").html("<%=j render partial: "reviews/form", locals: { product: @product, review: @review } %>");
const rating = $('#rating').val();
updateStars(rating);

function updateStars(rating) {
    $('.star').removeClass('active');
    $('.star:lt(' + rating + ')').addClass('active');
}

app/views/reviews/new.js.erb
$("#review-target").html("<%=j render partial: "reviews/form", locals: { product: @product, review: @review } %>");